name: Crypto Scanner

on:
  schedule:
    - cron: '0,45 7-20 * * *' # Runs at 08:00, 08:45, ..., 21:00 BST (UTC adjusted)
  workflow_dispatch:

jobs:
  scan-and-alert:
    runs-on: ubuntu-latest
    env:
      COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
      TAAPI_API_KEY: ${{ secrets.TAAPI_API_KEY }}
      CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
      COINMARKETCAL_API_KEY: ${{ secrets.COINMARKETCAL_API_KEY }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scanner & Send Alerts
        run: python app.py
 
